import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import * as api from "@/lib/api";
import { SiteHeader } from "@/widgets/header";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: profile의 property에 session의 property가 그대로 있기 때문에
  // TODO: profile만 사용해도 무방할 것 같지만, session은 login check용을 위해 목적을 분리하면 따로 사용할만 한 듯 함.
  // TODO: 추후 고민해보기
  const [categories, profile, session] = await Promise.all([
    api.getAllCategories().then((res) => res.data),
    api
      .getProfile()
      .then((res) => res.data)
      .catch((error) => {
        console.error(error);
        return undefined;
      }),
    auth(),
  ]);

  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SiteHeader
            categories={categories ?? []}
            profile={profile}
            session={session}
          />
          <main>{children}</main>
        </Providers>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
